//! The Ardana logo: the logo kit's horizontal lockup, as ardana.ai's nav draws it, inline so it takes the page's ink
//! (white in the dark scheme).

use leptos::prelude::*;

/// The lockup: the kit's tight horizontal logo (`brand/src/logo-tight.svg`, generated by the kit's `build.py`) in
/// `currentColor`, the same drawing as the landing's `Logo.svelte`. See `brand/README.md`.
const LOCKUP: &str = include_str!("../../brand/ardana-logo.svg");

/// The lockup, named "Ardana"; CSS sets its height (`.logo svg`).
#[component]
pub fn Logo(#[prop(optional)] class: &'static str) -> impl IntoView {
    view! { <span class=format!("logo {class}") role="img" aria-label="Ardana" inner_html=LOCKUP></span> }
}
