[package]
name = "ardana-playground"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
ardana-api.workspace = true
indexmap.workspace = true
js-sys.workspace = true
leptos.workspace = true
lz-str.workspace = true
serde.workspace = true
serde_json.workspace = true
wasm-bindgen.workspace = true
wasm-bindgen-futures.workspace = true
web-sys = { workspace = true, features = [
    "Clipboard",
    "Document",
    "Element",
    "Headers",
    "HtmlElement",
    "HtmlInputElement",
    "KeyboardEvent",
    "Location",
    "MediaQueryList",
    "Navigator",
    "Node",
    "Performance",
    "Request",
    "RequestInit",
    "Response",
    "ScrollBehavior",
    "ScrollIntoViewOptions",
    "ScrollLogicalPosition",
    "DomRect",
    "DomTokenList",
    "FocusOptions",
    "Storage",
    "UrlSearchParams",
    "Window",
] }
