[package]
name = "ardana-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
ardana-api.workspace = true
ardana-core.workspace = true
ardana-registry.workspace = true
axum.workspace = true
clap = { workspace = true, features = ["env"] }
http-body.workspace = true
memory-serve = { workspace = true, features = ["force-embed"] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "net", "time", "sync", "signal", "macros", "fs", "io-util"] }
tower-http = { workspace = true, features = ["compression-br", "compression-gzip"] }

[build-dependencies]
memory-serve.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
tower = { workspace = true, features = ["util"] }
